# Generated by Django 4.1.7 on 2023-03-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='descriptions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
